class AppString {
  static const baseUrl = "https://myfestivalcard.glitch.me/api/festival/";
  static const diwali = "diwali";
  static const uttrayan = "uttrayan";
  static const holi = "holi";
  static const mahashivratri = "mahashivratri";
  static const by = "By";
  static const byClickOnTech = "Click on Tech";
  static const pleaseFillSomeDetail = "Please fill some detail to";
  static const prepareCard = "Prepare Card";
  static const companyLogo = "Company Logo";
  static const companyName = "Company Name:";
  static const companyAdd = "Company Adress:";
  static const city = "City:";
  static const mobileNo = "Mobile No:";
  static const emailadd = "Email Adress:";
  static const next = "NEXT";
  static const festivals = "Festivals.....";
  static const festivalNm = "Festival Name";
  static const dateTime = "Date and Time";
  static const home = "Home";
  static const insta = "Instagram Id";
  static const fb = "Facebook Id";
  static const share = "Share";
  static const profile = "Profile";
  static const chooseFormat = "Please Select Image";
  static const chooseColorBg = "Set Logo Position";
  static const wooHoo = "Woohooo.....";
  static const download = "DOWNLOAD";
  static const yourCardIsReady = "Your Card is Ready";
  static const topLeft = "Top Left";
  static const bottomLeft = "Bottom Left";
  static const topRight = "Top Right";
  static const bottomRight = "Bottom Right";
  static const imgDwlSuccess = "Image Download Successfully";
  static const ok = "OK";
  static const plzSelectImg =
      "Please select Image"; //static const share = "Share";
}
